<a href="https://colab.research.google.com/github/DivyTiwari-ship-it/EEG_Dataset/blob/main/EEG_Dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns

In [11]:
df = pd.read_csv('features_raw.csv')
df.head()

,Fp1,AF3,F3,F7,FC5,FC1,C3,T7,CP5,CP1,...,Cz,C4,T8,CP6,CP2,P4,P8,PO4,O2,Unnamed: 32
0,0.057813,-1.335266,4.640480,0.219573,7.473817,2.314842,1.918097,-9.257533,9.089943,-7.104519,...,-2.241480,1.415335,2.406646,12.864059,4.021099,-2.828598,-2.588735,2.637905,-5.226618,NaN
1,1.367408,10.259654,3.345409,7.897852,-2.446051,-1.655035,-6.301423,-7.290317,-3.546453,-5.705187,...,-2.568397,-5.651418,-0.096730,-4.930759,-1.722504,-6.111309,0.094893,-3.521353,1.887093,NaN
2,-1.783132,4.133553,-0.951680,-1.624803,-1.827309,-2.280364,-2.279225,9.151344,-0.239575,-0.057604,...,-2.132823,-0.521117,8.605298,-4.499946,-3.232839,-4.249645,-3.687167,-7.383004,-4.489537,NaN
3,-3.690217,-0.814000,2.295469,0.901445,8.323679,1.127906,6.356886,11.642082,9.354154,-1.662478,...,-0.506117,-1.154866,-3.940251,7.390881,2.129897,-0.794675,-1.959021,2.774530,-6.323060,NaN
4,2.137114,6.420466,6.122230,10.015321,3.106394,3.183129,3.658535,4.571793,4.917712,-2.325940,...,1.813907,-6.444635,-27.680880,0.641364,1.996658,-0.445779,2.614021,6.161845,3.308816,NaN

In [4]:
df.describe()

,Fp1,AF3,F3,F7,FC5,FC1,C3,T7,CP5,CP1,...,Cz,C4,T8,CP6,CP2,P4,P8,PO4,O2,Unnamed: 32
count,8064.000000,8064.000000,8064.000000,8064.000000,8064.000000,8064.000000,8064.000000,8064.000000,8064.000000,8064.000000,...,8064.000000,8064.000000,8064.000000,8064.000000,8064.000000,8064.000000,8064.000000,8064.000000,8064.000000,0.0
mean,-0.030110,0.049626,-0.000615,0.012063,-0.072324,-0.005855,-0.051846,0.080661,-0.123370,0.048696,...,0.022278,0.005247,0.089107,-0.143788,-0.063250,-0.009944,0.085996,-0.150934,-0.025165,NaN
std,4.303870,19.050580,4.949803,19.530056,14.974316,5.223861,14.165469,20.447003,24.640017,12.291358,...,3.967493,11.566574,23.461405,37.118809,21.967885,13.279541,12.283903,37.205713,9.351170,NaN
min,-21.068011,-174.162043,-32.576432,-119.687503,-104.400666,-31.009221,-102.940922,-175.751521,-181.618505,-107.664139,...,-27.511152,-63.660644,-190.817674,-264.707312,-154.697176,-92.928548,-107.039803,-257.126150,-61.072350,NaN
25%,-2.741710,-6.946013,-2.907836,-8.685504,-5.854239,-2.613004,-4.874130,-9.294624,-7.736768,-5.723207,...,-2.428667,-5.443370,-12.156545,-11.501669,-7.169325,-4.741264,-4.863120,-12.069369,-4.147790,NaN
50%,0.065934,0.079142,0.016822,0.050682,-0.196773,-0.023871,-0.055134,0.028703,-0.234875,0.190146,...,0.046393,0.014605,0.209449,-0.361638,-0.106215,0.022058,0.068265,-0.410909,-0.133808,NaN
75%,2.800696,7.236850,2.968202,8.973624,5.405050,2.623072,4.686449,9.383725,7.317881,5.932243,...,2.435290,5.497645,12.253631,11.114534,6.803120,4.486082,5.201910,11.340294,4.129460,NaN
max,18.633981,128.729493,33.843385,120.164457,140.707711,38.313366,133.738083,129.284111,247.950230,86.087539,...,23.901393,73.879081,154.613511,366.740914,214.349394,126.611391,86.421457,361.662396,84.408689,NaN

In [7]:
df.isnull().sum()/len(df) * 100

Fp1              0.0
AF3              0.0
F3               0.0
F7               0.0
FC5              0.0
FC1              0.0
C3               0.0
T7               0.0
CP5              0.0
CP1              0.0
P3               0.0
P7               0.0
PO3              0.0
O1               0.0
Oz               0.0
Pz               0.0
Fp2              0.0
AF4              0.0
Fz               0.0
F4               0.0
F8               0.0
FC6              0.0
FC2              0.0
Cz               0.0
C4               0.0
T8               0.0
CP6              0.0
CP2              0.0
P4               0.0
P8               0.0
PO4              0.0
O2               0.0
Unnamed: 32    100.0
dtype: float64

In [13]:
df.drop(columns=['Unnamed: 32'], inplace=True)

In [14]:
df.isnull().sum().sum()

np.int64(0)

In [15]:
df.head()

,Fp1,AF3,F3,F7,FC5,FC1,C3,T7,CP5,CP1,...,FC2,Cz,C4,T8,CP6,CP2,P4,P8,PO4,O2
0,0.057813,-1.335266,4.640480,0.219573,7.473817,2.314842,1.918097,-9.257533,9.089943,-7.104519,...,-30.579542,-2.241480,1.415335,2.406646,12.864059,4.021099,-2.828598,-2.588735,2.637905,-5.226618
1,1.367408,10.259654,3.345409,7.897852,-2.446051,-1.655035,-6.301423,-7.290317,-3.546453,-5.705187,...,-1.290516,-2.568397,-5.651418,-0.096730,-4.930759,-1.722504,-6.111309,0.094893,-3.521353,1.887093
2,-1.783132,4.133553,-0.951680,-1.624803,-1.827309,-2.280364,-2.279225,9.151344,-0.239575,-0.057604,...,11.424923,-2.132823,-0.521117,8.605298,-4.499946,-3.232839,-4.249645,-3.687167,-7.383004,-4.489537
3,-3.690217,-0.814000,2.295469,0.901445,8.323679,1.127906,6.356886,11.642082,9.354154,-1.662478,...,-14.721411,-0.506117,-1.154866,-3.940251,7.390881,2.129897,-0.794675,-1.959021,2.774530,-6.323060
4,2.137114,6.420466,6.122230,10.015321,3.106394,3.183129,3.658535,4.571793,4.917712,-2.325940,...,-13.815090,1.813907,-6.444635,-27.680880,0.641364,1.996658,-0.445779,2.614021,6.161845,3.308816

In [18]:
print(df.columns)

Index(['Fp1', 'AF3', 'F3', 'F7', 'FC5', 'FC1', 'C3', 'T7', 'CP5', 'CP1', 'P3',
       'P7', 'PO3', 'O1', 'Oz', 'Pz', 'Fp2', 'AF4', 'Fz', 'F4', 'F8', 'FC6',
       'FC2', 'Cz', 'C4', 'T8', 'CP6', 'CP2', 'P4', 'P8', 'PO4', 'O2'],
      dtype='object')

In [22]:
esg_cols = ['Fp1', 'AF3', 'F3', 'F7', 'FC5', 'FC1', 'C3', 'T7', 'CP5', 'CP1', 'P3',
       'P7', 'PO3', 'O1', 'Oz', 'Pz', 'Fp2', 'AF4', 'Fz', 'F4', 'F8', 'FC6',
       'FC2', 'Cz', 'C4', 'T8', 'CP6', 'CP2', 'P4', 'P8', 'PO4', 'O2']

In [24]:
df['mean'] = df[esg_cols].mean(axis=1)
df['std'] = df[esg_cols].std(axis=1)
df['max'] = df[esg_cols].max(axis=1)
df['min'] = df[esg_cols].min(axis=1)
df['range'] = df['max'] - df['min']

In [28]:
from scipy.stats import skew, kurtosis

df['skewness'] = df[esg_cols].apply(skew,axis=1)
df['kurtosis'] = df[esg_cols].apply(kurtosis,axis=1)

In [29]:
df.shape
df.head()

,Fp1,AF3,F3,F7,FC5,FC1,C3,T7,CP5,CP1,...,P8,PO4,O2,mean,std,max,min,range,skewness,kurtosis
0,0.057813,-1.335266,4.640480,0.219573,7.473817,2.314842,1.918097,-9.257533,9.089943,-7.104519,...,-2.588735,2.637905,-5.226618,-3.608225e-16,7.609297,12.864059,-30.579542,43.443602,-1.922536,6.321127
1,1.367408,10.259654,3.345409,7.897852,-2.446051,-1.655035,-6.301423,-7.290317,-3.546453,-5.705187,...,0.094893,-3.521353,1.887093,-1.845746e-15,4.379032,10.259654,-7.290317,17.549971,0.302810,-0.505597
2,-1.783132,4.133553,-0.951680,-1.624803,-1.827309,-2.280364,-2.279225,9.151344,-0.239575,-0.057604,...,-3.687167,-7.383004,-4.489537,8.326673e-17,4.249239,11.424923,-7.383004,18.807927,1.025919,0.691151
3,-3.690217,-0.814000,2.295469,0.901445,8.323679,1.127906,6.356886,11.642082,9.354154,-1.662478,...,-1.959021,2.774530,-6.323060,8.326673e-17,5.295382,11.642082,-14.721411,26.363493,-0.070389,0.761390
4,2.137114,6.420466,6.122230,10.015321,3.106394,3.183129,3.658535,4.571793,4.917712,-2.325940,...,2.614021,6.161845,3.308816,5.273559e-16,7.049388,10.015321,-27.680880,37.696200,-2.116677,5.754796

In [30]:
df.columns.tolist()

['Fp1',
 'AF3',
 'F3',
 'F7',
 'FC5',
 'FC1',
 'C3',
 'T7',
 'CP5',
 'CP1',
 'P3',
 'P7',
 'PO3',
 'O1',
 'Oz',
 'Pz',
 'Fp2',
 'AF4',
 'Fz',
 'F4',
 'F8',
 'FC6',
 'FC2',
 'Cz',
 'C4',
 'T8',
 'CP6',
 'CP2',
 'P4',
 'P8',
 'PO4',
 'O2',
 'mean',
 'std',
 'max',
 'min',
 'range',
 'skewness',
 'kurtosis']

In [31]:
df.shape

(8064, 39)

In [32]:
df.head(2)

,Fp1,AF3,F3,F7,FC5,FC1,C3,T7,CP5,CP1,...,P8,PO4,O2,mean,std,max,min,range,skewness,kurtosis
0,0.057813,-1.335266,4.640480,0.219573,7.473817,2.314842,1.918097,-9.257533,9.089943,-7.104519,...,-2.588735,2.637905,-5.226618,-3.608225e-16,7.609297,12.864059,-30.579542,43.443602,-1.922536,6.321127
1,1.367408,10.259654,3.345409,7.897852,-2.446051,-1.655035,-6.301423,-7.290317,-3.546453,-5.705187,...,0.094893,-3.521353,1.887093,-1.845746e-15,4.379032,10.259654,-7.290317,17.549971,0.302810,-0.505597

In [34]:
df['mean'].describe()

count    8.064000e+03
mean    -3.906602e-18
std      1.468985e-15
min     -1.865175e-14
25%     -4.874573e-16
50%      0.000000e+00
75%      4.484260e-16
max      1.532108e-14
Name: mean, dtype: float64

In [35]:
df['std'].describe()

count    8064.000000
mean       14.950897
std        17.423060
min         2.104130
25%         6.657955
50%         9.605081
75%        15.411221
max       211.670297
Name: std, dtype: float64

In [42]:
def label_emotion(std_val):
  if std_val>15:
    return 'Excited'
  elif std_val<6.6:
    return 'Calm'
  else :
    return 'Focused'

df['emotion'] = df['std'].apply(label_emotion)

In [43]:
df['emotion'].value_counts()

emotion
Focused    3992
Excited    2106
Calm       1966
Name: count, dtype: int64

In [45]:
feature_cols = esg_cols + ['mean', 'std', 'max', 'min', 'range', 'skewness', 'kurtosis']

X = df[feature_cols]
y = df['emotion']

print(X.shape)
print(y.value_counts())

(8064, 39)
emotion
Focused    3992
Excited    2106
Calm       1966
Name: count, dtype: int64

In [46]:
from sklearn.model_selection import train_test_split

Xtrain , Xtest, ytrain , ytest = train_test_split(X,y, test_size=0.2, random_state=42)

print(Xtrain.shape)

(6451, 39)

In [49]:
from xgboost import XGBClassifier
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y_train_label = le.fit_transform(ytrain)
y_test_label = le.transform(ytest)

model = XGBClassifier(n_estimators=500, max_depth=5 , random_state=42)

model.fit(Xtrain, y_train_label)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              feature_weights=None, gamma=None, grow_policy=None,
              importance_type=None, interaction_constraints=None,
              learning_rate=None, max_bin=None, max_cat_threshold=None,
              max_cat_to_onehot=None, max_delta_step=None, max_depth=5,
              max_leaves=None, min_child_weight=None, missing=nan,
              monotone_constraints=None, multi_strategy=None, n_estimators=500,
              n_jobs=None, num_parallel_tree=None, ...)

In [50]:
from sklearn.metrics import accuracy_score

ypred = model.predict(Xtest)

accuracy = accuracy_score(y_test_label , ypred)

print(f'Accuracy of ESG by XGB is {accuracy}')

Accuracy of ESG by XGB is 0.9944203347799132

In [52]:
from sklearn.metrics import classification_report

y_pred = model.predict(Xtest)
y_pred_labels = le.inverse_transform(y_pred)
y_test_labels = le.inverse_transform(y_test_label)

print(classification_report(y_test_labels, y_pred_labels))

              precision    recall  f1-score   support

        Calm       0.99      1.00      0.99       387
     Excited       0.99      1.00      0.99       429
     Focused       1.00      0.99      0.99       797

    accuracy                           0.99      1613
   macro avg       0.99      1.00      0.99      1613
weighted avg       0.99      0.99      0.99      1613

In [53]:
import pickle

with open('eeg_emotion_model.pkl', 'wb') as f:
    pickle.dump(model, f)

with open('label_encoder.pkl', 'wb') as f:
    pickle.dump(le, f)

print("Model saved!")

Model saved!

In [54]:
import os
os.listdir()

['.config',
 'eeg_emotion_model.pkl',
 'label_encoder.pkl',
 'features_raw.csv',
 'sample_data']